wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 64
learning_rate:
  value: 0.03948901317096603
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: nag
weight_decay:
  value: 1.0e-05
weight_init:
  value: xavier
