wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.02108995333549001
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: sgd
weight_decay:
  value: 1.0e-05
weight_init:
  value: random
