wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 128
learning_rate:
  value: 0.07258437760568386
loss:
  value: mean_squared_error
num_layers:
  value: 3
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: xavier
