wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 256
learning_rate:
  value: 0.07257552075256203
loss:
  value: mean_squared_error
num_layers:
  value: 2
optimizer:
  value: momentum
weight_decay:
  value: 0.0001
weight_init:
  value: xavier
