wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_size:
  value: 256
learning_rate:
  value: 0.000925318227934965
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: sgd
weight_decay:
  value: 1.0e-05
weight_init:
  value: xavier
