_wandb:
    value:
        cli_version: 0.25.0
        e:
            kf8icmaqntm333v6txsrgqcwyomt1wcf:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                codePath: src/sweep.py
                codePathLocal: src/sweep.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "275386945536"
                email: ashishmeshram229@gmail.com
                executable: /Library/Frameworks/Python.framework/Versions/3.13/bin/python3
                host: Ashishs-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-26.3-arm64-arm-64bit-Mach-O
                program: /Users/ashishmeshram/Documents/IITM - ACADEMICS/SEM2/COURSES/DL/ASSIGNMENT1/da6401_assignment_1/src/sweep.py
                python: CPython 3.13.5
                root: /Users/ashishmeshram/Documents/IITM - ACADEMICS/SEM2/COURSES/DL/ASSIGNMENT1/da6401_assignment_1
                startedAt: "2026-03-03T13:16:23.330618Z"
                writerId: kf8icmaqntm333v6txsrgqcwyomt1wcf
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 105
            "3":
                - 2
                - 14
            "4": 3.13.5
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
activation:
    value: tanh
batch_size:
    value: 32
dataset:
    value: mnist
epochs:
    value: 20
hidden_size:
    value: 64
learning_rate:
    value: 0.007771814259594133
loss:
    value: cross_entropy
num_layers:
    value: 4
optimizer:
    value: nag
weight_decay:
    value: 1e-05
weight_init:
    value: xavier
