_wandb:
    value:
        cli_version: 0.25.0
        e:
            n61i4yvadi4ipqah80srqqpj6gxjkddv:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                args:
                    - -d
                    - fashion_mnist
                    - -e
                    - "15"
                    - -b
                    - "64"
                    - -l
                    - cross_entropy
                    - -o
                    - rmsprop
                    - -lr
                    - "0.001"
                    - -nhl
                    - "3"
                    - -sz
                    - "128"
                    - "128"
                    - "128"
                    - -a
                    - relu
                    - relu
                    - relu
                    - -wi
                    - xavier
                    - -wg
                    - 2.10_Fashion_Transfer
                    - -wp
                    - da6401_assignment_1
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "275427643392"
                email: ashishmeshram229@gmail.com
                executable: /Library/Frameworks/Python.framework/Versions/3.13/bin/python3
                host: Ashishs-MacBook-Air.local
                memory:
                    total: "17179869184"
                os: macOS-26.3-arm64-arm-64bit-Mach-O
                program: /Users/ashishmeshram/Documents/IITM - ACADEMICS/SEM2/COURSES/DL/ASSIGNMENT1/da6401_assignment_1/src/train.py
                python: CPython 3.13.5
                root: /Users/ashishmeshram/Documents/IITM - ACADEMICS/SEM2/COURSES/DL/ASSIGNMENT1/da6401_assignment_1
                startedAt: "2026-03-03T13:30:52.026274Z"
                writerId: n61i4yvadi4ipqah80srqqpj6gxjkddv
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
activation:
    value:
        - relu
        - relu
        - relu
batch_size:
    value: 64
config_path:
    value: best_config.json
dataset:
    value: fashion_mnist
epochs:
    value: 15
hidden_size:
    value:
        - 128
        - 128
        - 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
model_path:
    value: best_model.npy
num_layers:
    value: 3
optimizer:
    value: rmsprop
wandb_group:
    value: 2.10_Fashion_Transfer
wandb_project:
    value: da6401_assignment_1
weight_decay:
    value: 0
weight_init:
    value: xavier
